Feature/get user by cpf
ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba pull request #39
Opened 2023-09-17 23:17 UTC by NyKaren

backend-sistema-academico-ic-ufba #7
endpoint: sistemaacademico/user/cpf?cpf=123456789012

2023-09-18 00:57 UTC, VitaminaNescau requested changes
Não é necessário escrever os métodos set e get nas class q contém Lombok, utilizando @Data ou @Gette @Sett, já se obtém esses métodos(que já estão implementados)

2023-09-19 02:04 UTC, NyKaren commented
https://github.com/ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba/pull/39#pullrequestreview-1630175986
Obrigada, @VitaminaNescau 
Estou removendo os métodos, Já já sybo pro github

2023-09-19 02:15 UTC, NyKaren commented
@VitaminaNescau Poderia olhar de novo?

2023-09-19 02:28 UTC, VitaminaNescau approved these changes

2023-09-19 02:29 UTC, merged