Iniciando integração de disciplinas com frontend
ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba pull request #80
Opened 2023-10-15 23:47 UTC by laviodias

2023-10-23 08:30 UTC, NyKaren requested changes
@laviodias Poderia dar uma olhada nas perguntas que fiz na PR? Obrigada!

2023-10-23 08:30 UTC, NyKaren commented on src/main/java/com/ic045/sistemaacademico/controller/vos/request/InsertDisciplinaRequest.java
> +        int semestre
@laviodias requisitos e bibliografia estão sendo utilizados na integração que Glauber está trabalhando. Olhando aqui foram removidas. Essas remoções são necessárias?

2023-10-23 08:30 UTC, NyKaren commented on src/main/java/com/ic045/sistemaacademico/controller/DisciplinaController.java
> +				,insertDisciplina.semestre());
@laviodias requisitos e bibliografia estão sendo utilizados na integração que Glauber está trabalhando. Olhando aqui foram removidas. Essas remoções são necessárias?

2023-10-23 10:51 UTC, laviodias commented on src/main/java/com/ic045/sistemaacademico/controller/DisciplinaController.java
> +				,insertDisciplina.semestre());
Talvez eu tenha me confundido com a linguagem, já que não uso Java.
Existe a possibilidade desses campos serem opcionais? Se eu tento colocar campos não obrigatórios neste construtor, recebo um erro no build...

2023-10-23 16:38 UTC, NyKaren commented on src/main/java/com/ic045/sistemaacademico/controller/DisciplinaController.java
> +				,insertDisciplina.semestre());
Sem problemas. Pelo que vi aqui, no merge você acabou removendo esses campos do modelo de insert, [InsertDisciplinaRequest.java](https://github.com/ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba/pull/80/files/ade6f9899eea1a8b1a240a8520e4c012b2babee4#diff-ccd3cf6e5c6d4dc4cfd1fb53aa821cb42ff2f8da9d2fe37ed5ac909bcec72bd9). Poderia tentar ao adicionar esses campos no insert e no build? Acredito que por isso tenha dado erro.
Por favor, atualiza o https://github.com/ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba/pull/80/files/ade6f9899eea1a8b1a240a8520e4c012b2babee4#diff-7f148b1d99361fa9fe2a88f2009f50179de9cc7f46aea5240411c21289d2f36a também. Obrigada, Lávio.

2023-10-23 16:50 UTC, laviodias commented on src/main/java/com/ic045/sistemaacademico/controller/DisciplinaController.java
> +				,insertDisciplina.semestre());
Mesmo que eu adicione os campos no modelo, ainda ocorre o erro quando eu coloco eles no construtor.
![image](https://github.com/ic045-sistemaacademico-2023/backend-sistema-academico-ic-ufba/assets/44332001/77b68cf3-c10d-4e75-9056-4716f8383126)

2023-10-26 22:08 UTC, NyKaren approved these changes

2023-10-26 22:08 UTC, merged